# Build settings
markdown: kramdown
permalink: pretty

baseurl: /another-portfolio
url: http://crystalcastles.github.io

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested
  
# jekyll serve --watch -H $IP -P $PORT --baseurl ""