# Site settings
title: Artists Theme
email: artist@email
description: "Thinker // Designer // YouTuber"

bg-img: hero-bg.jpg
avatar: face.jpg
blurb: <p><strong>
      Lorem ipsum dolor sit amet</strong>, consectetur adipiscing elit, sed do eiusmod 
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo 
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse 
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat
      non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>

# Build settings
markdown: kramdown
permalink: pretty

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested
  
# jekyll serve --watch -H $IP -P $PORT --baseurl ""