# Site settings
title: Artists Theme
email: artist@email
description: "Thinker // Designer // YouTuber"

# Build settings
markdown: kramdown
permalink: pretty

include: ['_includes/work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested
  
# jekyll serve --watch -H $IP -P $PORT --baseurl ""